// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq7i3kwmwtOrr-oSUqG5Vv4ZyBHIL2j4s',
    appId: '1:81787462477:web:3050cd5290ed5279facd04',
    messagingSenderId: '81787462477',
    projectId: 'library-seat-booking-0823',
    authDomain: 'library-seat-booking-0823.firebaseapp.com',
    storageBucket: 'library-seat-booking-0823.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA02ZZX9Ta3m0o3uyWIH6OLzGT9mEJLmac',
    appId: '1:81787462477:android:c9ccbfb80d620f00facd04',
    messagingSenderId: '81787462477',
    projectId: 'library-seat-booking-0823',
    storageBucket: 'library-seat-booking-0823.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaKN1dCSD8gmDAcRsBhtlBQPQZwNaL9lw',
    appId: '1:81787462477:ios:221ba0c7f645b234facd04',
    messagingSenderId: '81787462477',
    projectId: 'library-seat-booking-0823',
    storageBucket: 'library-seat-booking-0823.firebasestorage.app',
    iosBundleId: 'com.example.librarySeatBooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaKN1dCSD8gmDAcRsBhtlBQPQZwNaL9lw',
    appId: '1:81787462477:ios:221ba0c7f645b234facd04',
    messagingSenderId: '81787462477',
    projectId: 'library-seat-booking-0823',
    storageBucket: 'library-seat-booking-0823.firebasestorage.app',
    iosBundleId: 'com.example.librarySeatBooking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAq7i3kwmwtOrr-oSUqG5Vv4ZyBHIL2j4s',
    appId: '1:81787462477:web:3769ae6657826893facd04',
    messagingSenderId: '81787462477',
    projectId: 'library-seat-booking-0823',
    authDomain: 'library-seat-booking-0823.firebaseapp.com',
    storageBucket: 'library-seat-booking-0823.firebasestorage.app',
  );
}
